---
title: "AFL Modelling of Performance Per Game"
output: html_notebook
---
```{r}
source("../../utilities/DBDA2E-utilities.R")
source("../../utilities/MoreUtilities.R")
library(ggplot2)
library(ggpubr)
library(ks)
library(rjags)
library(runjags)
library(benchmarkme)
```

## Read train and test sets from files.
```{r}
train <- read.csv("../../data/train_performance.csv")
test <- read.csv("../../data/test_performance.csv")
test_balanced <- read.csv("../../data/test_balanced_performance.csv")
performance <- read.csv("../../data/performance.csv")
```

# Modelling
```{r}
colnames(train[,1:22])
y <- train$Brownlow.Votes
x <- as.matrix(train[,1:22])
xPred = as.matrix(test[,1:22])

dataList = list(
  x = x,
  colCount = ncol(x), 
  
  y = y,
  rowCount = length(y),
  
  xPred = xPred,
  predCount = nrow(xPred)
)

summary(x)
```


```{r}
table(x)
```
### JAGS Model
```{r}
	modelString = "
	data {
	  yMean <- mean(y)
	  
	  # There was no expert information and because we have a lot of data, we 
	  # made the variances very high and mu = 0 so that the model can converge 
	  # without priors effecting the results much.
	  mu0 <- yMean
	  for (i in 1:colCount) {
	    mu[i] <- 0
	  }
	  
	  Var0   <- 1000 # Set simply to 1
	  for (i in 1:colCount) {
	    Var[i] <- 1000
	  }
	}
	
	# Model
	model {
	  beta0   ~ dnorm(mu0,  1/Var0)
	  for (j in 1:colCount) {
	    beta[j] ~ dnorm(mu[j], 1/Var[j])
	  }
	  
	  precision ~ dexp(1/0.25) 
	  
	  for (i in 1:rowCount) {
	  
	    # Normal Likelihood
	    y[i] ~ dnorm(beta0 + sum(beta[1:colCount]*x[i,1:colCount]), precision)
	  }

    for (k in 1:predCount) {
      pred[k] <- beta0 + sum(beta[1:colCount]*xPred[k,1:colCount])
    }
}
"
	
	writeLines(modelString, con="TEMPmodel2.txt")
```
### Run JAGS
```{r}

parameters = c("beta0")
for ( i in 1:22){
  parameters = c(parameters, paste0("beta[",i,"]"))
}
for ( i in 1:nrow(xPred)){
  parameters = c(parameters, paste0("pred[",i,"]"))
}

adaptSteps = 50
burnInSteps = 100
nChains = 2
thinSteps = 17
numSavedSteps = 250

nIter = ceiling( ( numSavedSteps * thinSteps ) / nChains )

startTime = proc.time()
# sink("debug2.txt")
runJagsOut <- run.jags( method="parallel" ,
                        model="TEMPmodel2.txt",
                        monitor=parameters,
                        data=dataList,
                        n.chains=nChains,
                        adapt=adaptSteps,
                        burnin=burnInSteps,
                        sample=numSavedSteps,
                        thin=thinSteps , summarise=FALSE , plots=FALSE )
stopTime = proc.time()
duration = stopTime - startTime
show(duration)
codaSamples = as.mcmc.list( runJagsOut )
# sink()
save( codaSamples , file=paste("Run1","Mcmc.Rdata",sep="") )
save.image(file='Run1.RData')
```
# Load save
```{r}
load.image(file='Run1.RData')
```

### Results
```{r}

# ============= Display Results ============
diagMCMC( codaSamples , parName="beta0" )
for ( i in 1:22) {
  diagMCMC( codaSamples , parName=paste0("beta[",i,"]") )
}

compVal <- data.frame(
  "beta0" = 0, 
  "beta[1]" = 0,
  "beta[2]" = 0, 
  "beta[3]" = 0, 
  "beta[4]" =  0, 
  "beta[5]" =  0,
  "beta[6]" =  0,
  "beta[7]" =  0,
  "beta[8]" =  0,
  "beta[9]" =  0,
  "beta[10]" =  0,
  "beta[11]" =  0,
  "beta[12]" =  0,
  "beta[13]" =  0,
  "beta[14]" =  0,
  "beta[15]" =  0,
  "beta[16]" =  0,
  "beta[17]" =  0,
  "beta[18]" =  0,
  "beta[19]" =  0,
  "beta[20]" =  0,
  "beta[21]" =  0,
  "beta[22]" =  0,
  check.names=FALSE)


summaryInfo <- smryMCMC( codaSamples = codaSamples , compVal = compVal, saveName="SummaryInfo" )


plotMCMC_HD( codaSamples = codaSamples, data = train_balanced, xName=c(
  "Disposals",
  "Kicks",
  "Marks",
  "Handballs",
  "Goals",
  "Behinds",
  "Hit.Outs",
  "Tackles",
  "Rebounds",
  "Inside.50s",
  "Clearances",
  "Clangers",
  "Frees",
  "Frees.Against",
  "Contested.Possessions",
  "Uncontested.Possessions",
  "Contested.Marks",
  "Marks.Inside.50",
  "One.Percenters",
  "Bounces",
  "Goal.Assists",
  "X..Played"
 ),
 yName="Brownlow.Votes", compVal = compVal, preds = TRUE)
```

```{r}
plotMCMC_HD( codaSamples = codaSamples, data = train_balanced, xName=c("Behinds", "Bounces", "Clangers", "Clearances", "Contested.Marks", "Contested.Possessions",
    "Disposals", "Frees", "Frees.Against", "Goal.Assists", "Goals", "Handballs",
    "Hit.Outs", "Inside.50s", "Kicks", "Marks", "Marks.Inside.50", "One.Percenters", "Rebounds",
    "Tackles", "Uncontested.Possessions"), yName="Brownlow.Votes", compVal = compVal, preds = TRUE)
```

```{r}
pred <- c()
mode <- summaryInfo[,"Mode"]
xPred2 = as.matrix(test_balanced[,1:22])
for (k in 1:nrow(xPred)) {
 
  pred[k] <- mode["beta0"] +
    (mode["beta[1]"]*xPred2[k,1]) +
    (mode["beta[2]"]*xPred2[k,2]) + 
    (mode["beta[3]"]*xPred2[k,3]) + 
    (mode["beta[4]"]*xPred2[k,4]) + 
    (mode["beta[5]"]*xPred2[k,5]) +
    (mode["beta[6]"]*xPred2[k,6]) +
    (mode["beta[7]"]*xPred2[k,7]) +
    (mode["beta[8]"]*xPred2[k,8]) +
    (mode["beta[9]"]*xPred2[k,9]) +
    (mode["beta[10]"]*xPred2[k,10]) +
    (mode["beta[11]"]*xPred2[k,11]) +
    (mode["beta[12]"]*xPred2[k,12]) +
    (mode["beta[13]"]*xPred2[k,13]) +
    (mode["beta[14]"]*xPred2[k,14]) +
    (mode["beta[15]"]*xPred2[k,15]) +
    (mode["beta[16]"]*xPred2[k,16]) +
    (mode["beta[17]"]*xPred2[k,17]) +
    (mode["beta[18]"]*xPred2[k,18]) +
    (mode["beta[19]"]*xPred2[k,19]) +
    (mode["beta[20]"]*xPred2[k,20]) +
    (mode["beta[21]"]*xPred2[k,21]) +
    (mode["beta[22]"]*xPred2[k,22])
}
```

# ============ Predictive check ============
```{r}
performance_test <- function (predictions) {
  real = c(test$Brownlow.Votes)
  length(predictions)
  length(real)
  n = length(real)
  print(paste("MAE:", sum(abs(predictions - real))/n))
  print(paste("MSE:", sum((real - predictions)^2)))
  print(paste("RMSE:", sqrt(mse/n)))
}

performance_test(pred)
```


```{r}
library(dplyr)
library(tidyr)

test$pred <- pred


leaderboard = c()
for (id in unlist(test$gameId[1])) {
  game <- test[test$gameId == id,]
  ordered <- game[order(-game$pred),]
  top_3_rows <- head(ordered, 3)
  
  # Reverse order so that brownlow predictions can be equal to index
  top_3_rows <- top_3_rows[order(top_3_rows$pred),]
  for (row in top_3_rows) {
    id_name = paste(row$displayName, row$playerId, sep="_")
    score <- 0
    if (!is.null(leaderboard[id_name])) {
      score <- leaderboard[id_name]
    }

    leaderboard[id_name] <- score +
  }
}
```

```{r}
hi = c()
!is.null(hi["yo"])
```
